# Generated by Django 5.0.3 on 2025-01-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_python', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_graph', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График уровня зарплат')),
                ('vacancy_graph', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График количества вакансий')),
                ('table', models.TextField(verbose_name='Таблица востребованности')),
            ],
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_graph_by_city', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График зарплат по городам')),
                ('vacancy_fraction_by_city', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График доли вакансий по городам')),
                ('table', models.TextField(verbose_name='Таблица географии')),
            ],
        ),
        migrations.CreateModel(
            name='LastVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('vacancy_name_to_parse', models.TextField(verbose_name='Вакансия для парсинга')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Описание профессии')),
                ('photo', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название таблицы')),
                ('table', models.TextField(verbose_name='Таблица')),
                ('skills_graph', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График по скиллам')),
            ],
        ),
        migrations.DeleteModel(
            name='LastVacancyModel',
        ),
    ]
